# Travis  is a continuous integration service to build, test and deploy the package

# adapted from https://github.com/scikit-learn/scikit-learn/blob/master/.travis.yml

# use travis only on the following branches for building
branches:
  only:
    - master
    - dev

language: shell  # 'language: python' is an error on Travis CI with macOS

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: xenial

env:
  global:
    - TRAVIS_DEPLOY_BRANCH="master"  # branch on which to deploy build artifacts and website
    - TRAVIS_DEPLOY_JOB_NAME="osx-py37"  # job on which to deploy website

    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

    - TEST_DIR=/tmp/sktime  # Directory where tests are run from
    - REQUIREMENTS="requirements.yml"

  # platforms and package environments to test
jobs:
  include:
    - name: "linux-py37"
      os: linux
      env:
      - PYTHON_VERSION=3.7
      - MINICONDA_VERSION=Miniconda3-latest-Linux-x86_64.sh
    - name: "osx-py36"
      os: osx
      env:
        - PYTHON_VERSION=3.6
        - MINICONDA_VERSION=Miniconda3-latest-MacOSX-x86_64.sh
    - name: "osx-py37"
      os: osx
      env:
      - PYTHON_VERSION=3.7
      - MINICONDA_VERSION=Miniconda3-latest-MacOSX-x86_64.sh
    - name: "osx-py38"
      os: osx
      env:
      - PYTHON_VERSION=3.8
      # Check available miniconda version: https://repo.anaconda.com/miniconda/
      - MINICONDA_VERSION=Miniconda3-py38_4.8.2-MacOSX-x86_64.sh

addons:
  # travis recommends to specify any additional necessary packages here,
  # rather than manually installing them in the install script
  homebrew:
    packages:
      - ccache
      - libomp
      - jq
      - pandoc
    update: true

install:
  - source build_tools/travis/install.sh  # build environment

script:
  - bash build_tools/travis/test_script.sh  # run unit tests

after_success:
  - source build_tools/travis/after_success.sh

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  # on master branch, deploy website and upload compiled files to Github
  - provider: pages
    skip-cleanup: true
    local_dir: "./documentation/build_doc_site/html"
    github-token: $GITHUB_TOKEN  # Generated in Github settings page of your repo, set in travis settings
    keep-history: false
    on:
        branch: $TRAVIS_DEPLOY_BRANCH
        condition: $TRAVIS_JOB_NAME = $TRAVIS_DEPLOY_JOB_NAME  # deploy only on macOS build
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true  # skip clean up which would delete build artifacts
    draft: true
    file_glob: true  # enable wildcards in file
    file: dist/*  # files to upload
    on:
        branch: $TRAVIS_DEPLOY_BRANCH
