# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

# adapted from
# - https://packaging.python.org/guides/supporting-windows-using-appveyor/ and
# - https://github.com/scikit-learn/scikit-learn/blob/master/appveyor.yml

branches:
  # whitelist
  only:
    - master
    - dev

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: https://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\build_tools\\appveyor\\run_with_env.cmd"
    TEST_DIR: "/tmp/sktime"

  matrix:
    - PYTHON_VERSION: "3.7"
      MINICONDA: C:\Miniconda37-x64
    - PYTHON_VERSION: "3.8.2"
      MINICONDA: C:\Miniconda38-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

platform:
    - x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"

# Because we only have a single worker, we don't want to waste precious
# appveyor CI time and make other PRs wait for repeated failures in a failing
# PR. The following option cancels pending jobs in a given PR after the first
# job failure in that specific PR.
matrix:
    fast_finish: true

# Not a .NET project, we build sktime in the install step instead
build: false

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rolling builds' option is supposed to serve the same
  # purpose but is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds.
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=500).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Set up conda environment
  - cmd: SET PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%
  - cmd: conda config --set always_yes true
  - cmd: conda update --quiet conda

  # Install dependencies
  - cmd: conda env create --name testenv --file requirements.yml
  - cmd: activate testenv
  - cmd: conda list  # list packages

  # Build wheels
  - cmd: python setup.py bdist_wheel bdist_wininst
  - ps: "ls dist"  # list built artifacts

  # Install the generated wheel package to test it
  - cmd: pip install --pre --no-index --find-links dist/ sktime

  # If there is a newer build queued for the same PR, cancel this one.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=500).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

test_script:
  # Change to a non-source folder to make sure we run the tests on the
  # installed library.
  - cmd: mkdir %TEST_DIR%
  - cmd: cd %TEST_DIR%
  - ps: >-
        if (Test-Path variable:global:CHECK_WARNINGS) {
            $env:PYTEST_ARGS = "-Werror::DeprecationWarning -Werror::FutureWarning -Werror::UserWarning"
        } else {
            $env:PYTEST_ARGS = ""
        }
  # Run tests
  - cmd: pytest --showlocals --durations=20 %PYTEST_ARGS% --pyargs sktime

  # Move back to the project folder
  - cmd: cd "../sktime"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.

# upload artifacts to Github releases
deploy:
  - provider: GitHub
    description: 'Appveyor build artifacts'
    auth_token:
      secure: I7Q//pymos/j6j6A6NmsxAdzi9YTJm0cCIha1LTDZOdrONHDACl2gZQ187ublAVk # your encrypted token from GitHub
    artifact: /.*\.whl/            # upload all wheel packages to release assets
    draft: true
    on:
      branch: master       # release on master branch only
      APPVEYOR_REPO_TAG: true