# adapted from
# - https://iscinumpy.gitlab.io/post/azure-devops-intro/
# - https://iscinumpy.gitlab.io/post/azure-devops-python-wheels/

variables:
  PACKAGE_NAME: sktime
  REQUIREMENTS: requirements.yml

trigger:
- master
- dev

jobs:
  - job: manylinux
    strategy:
      matrix:
        64x2010:  # 64 bit 2010
          arch: x86_64
          plat: manylinux2010_x86_64
          image: quay.io/pypa/manylinux2010_x86_64
          python.architecture: x64
        64x:  # 64 bit
          arch: x86_64
          plat: manylinux1_x86_64
          image: quay.io/pypa/manylinux1_x86_64
          python.architecture: x64
        86x:  # 32 bit
          arch: i686
          plat: manylinux1_i686
          image: quay.io/pypa/manylinux1_i686
          python.architecture: x86
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: build_tools/azure/build_manylinux_wheels.yml

