# adapted from
# - https://iscinumpy.gitlab.io/post/azure-devops-python-wheels/

variables:
  REQUIREMENT: build_tools/requirements.txt
  EXCLUDE_PYTHON_VERSIONS: (2.7 3.5)

trigger:
  - master
  - dev

pr:
  # Cancel if new commits are pushed to the same PR
  autoCancel: true

jobs:
  - job: manylinux
    strategy:
      matrix:
        64x2010:  # 64 bit 2010
          ARCH: x86_64
          PLATFORM: manylinux2010_x86_64
          IMAGE: quay.io/pypa/manylinux2010_x86_64
          PYTHON_ARCHITECTURE: x64
        64x:  # 64 bit
          ARCH: x86_64
          PLATFORM: manylinux1_x86_64
          IMAGE: quay.io/pypa/manylinux1_x86_64
          PYTHON_ARCHITECTURE: x64
        86x:  # 32 bit
          ARCH: i686
          PLATFORM: manylinux1_i686
          IMAGE: quay.io/pypa/manylinux1_i686
          PYTHON_ARCHITECTURE: x86
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: build_tools/azure/build_manylinux_wheels.yml

