channels:
  - conda-forge
dependencies:
  # core dependencies
  - python>=3.7
  - pip
  - pandas>=1.0.0
  - scikit-learn=0.22.*
  - statsmodels=0.11.*
  - numba
  # extra dependencies for testing, building and deploying
  - pytest
  - cython>=0.29.0
  # soft dependencies
  - tsfresh
  - pip:
    - scikit-posthocs
    - pmdarima
