channels:
  - conda-forge
dependencies:
  # core dependencies
  - python=3.7
  - pip
  - numpy=1.18.*
  - pandas=1.0.*
  - joblib=0.14.*
  - statsmodels=0.11.*
  - cython=0.29.*
  - numba
  # extra dependencies for testing, deploying
  - pytest
  - wheel
  # soft dependencies
  - tsfresh
  - pip:
    - scikit-posthocs
    - pmdarima
